version: '3.8'

services:
  main:
    image: mariadb:latest
    container_name: sonata_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: truenext
      MYSQL_DATABASE: sonata_next
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: sonata_redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: sonata_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: sonata_rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ server
      - "15672:15672"  # Management console
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mariadb_data:
    driver: local
  mongodb_data:
    driver: local
  rabbitmq_data:    # Define volume for RabbitMQ data persistence
    driver: local
