CREATE TABLE `users` (
  `id_user` INT NOT NULL,
  `fid_media_profile` INT NULL DEFAULT NULL,
  `fid_media_cover` INT NULL DEFAULT NULL,
  `fid_verification` INT NULL DEFAULT NULL,
  `user_status` CHAR(2) NULL DEFAULT 'PV',
  `user_level` TINYINT NULL DEFAULT 0,
  `user_username` VARCHAR(64) NOT NULL,
  `user_gender` VARCHAR(4) NULL DEFAULT 'M',
  `user_city` VARCHAR(64) NULL,
  `user_state` VARCHAR(64) NULL,
  `user_postal` VARCHAR(64) NULL,
  `user_country` VARCHAR(3) NULL,
  `user_latitude` DECIMAL(10,8) NULL DEFAULT 0,
  `user_longitude` DECIMAL(10,8) NULL DEFAULT 0,
  `user_joined` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `user_login` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `user_expires` DATE NULL DEFAULT '0000-00-00',
  `user_verified` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
  `user_age_min` TINYINT NULL DEFAULT 0,
  `user_age_max` TINYINT NULL DEFAULT 100,
  `user_popularity` INT NULL DEFAULT 999999,
  `user_count_images` INT NULL DEFAULT 0,
  `user_count_videos` INT NULL DEFAULT 0,
  `user_count_views` INT NULL DEFAULT 0,
  `user_count_forum` INT NULL DEFAULT 0,
  `user_score` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  INDEX `fid_media_profile` (`fid_media_profile` ASC),
  INDEX `fid_media_cover` (`fid_media_cover` ASC),
  INDEX `fid_verification` (`fid_verification` ASC),
  INDEX `user_status` (`user_status` ASC),
  INDEX `user_level` (`user_level` ASC),
  INDEX `user_username` (`user_username` ASC),
  INDEX `user_gender` (`user_gender` ASC),
  INDEX `user_city` (`user_city` ASC),
  INDEX `user_state` (`user_state` ASC),
  INDEX `user_postal` (`user_postal` ASC),
  INDEX `user_country` (`user_country` ASC),
  INDEX `user_latitude` (`user_latitude` ASC),
  INDEX `user_longitude` (`user_longitude` ASC),
  INDEX `user_joined` (`user_joined` ASC),
  INDEX `user_joined_desc` (`user_joined` DESC),
  INDEX `user_login` (`user_login` ASC),
  INDEX `user_login_desc` (`user_login` DESC),
  INDEX `user_expires` (`user_expires` ASC),
  INDEX `user_verified` (`user_verified` ASC),
  INDEX `user_verified_desc` (`user_verified` DESC),
  INDEX `user_age_min` (`user_age_min` ASC),
  INDEX `user_age_min_desc` (`user_age_min` DESC),
  INDEX `user_age_max` (`user_age_max` ASC),
  INDEX `user_age_max_desc` (`user_age_max` DESC),
  INDEX `user_popularity` (`user_popularity` ASC),
  INDEX `user_popularity_desc` (`user_popularity` DESC),
  INDEX `user_count_images` (`user_count_images` ASC),
  INDEX `user_count_images_desc` (`user_count_images` DESC),
  INDEX `user_count_videos` (`user_count_videos` ASC),
  INDEX `user_count_videos_desc` (`user_count_videos` DESC),
  INDEX `user_count_forum` (`user_count_forum` ASC),
  INDEX `user_count_forum_desc` (`user_count_forum` DESC),
  INDEX `user_score` (`user_score` ASC),
  INDEX `user_score_desc` (`user_score` DESC),
  UNIQUE INDEX `user_username_UNIQUE` (`user_username` ASC)
);
