CREATE TABLE `media` (
  `id_media` INT NOT NULL AUTO_INCREMENT,
  `fid_user` INT NULL DEFAULT NULL,
  `fid_user_approved` INT NULL DEFAULT NULL,
  `fid_area` INT NULL DEFAULT NULL,
  `fid_folder` INT NULL DEFAULT NULL,
  `media_status` VARCHAR(4) NULL DEFAULT 'PA',
  `media_type` VARCHAR(4) NULL,
  `media_area` VARCHAR(4) NULL,
  `media_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `media_approved` DATETIME NULL DEFAULT NULL,
  `media_classification` VARCHAR(4) NULL DEFAULT 'PA',
  `media_tags` VARCHAR(256) NULL,
  `media_description` VARCHAR(256) NULL,
  `media_dimension_x` INT NULL DEFAULT NULL,
  `media_dimension_y` VARCHAR(45) NULL DEFAULT NULL,
  `media_count_views` INT NULL DEFAULT 0,
  `media_count_downloads` INT NULL DEFAULT 0,
  `media_exif` TEXT NULL DEFAULT NULL,

  PRIMARY KEY (`id_media`),
  UNIQUE INDEX `id_media_UNIQUE` (`id_media` ASC) VISIBLE,
  INDEX `fid_user` (`fid_user` ASC),
  INDEX `fid_user_approved` (`fid_user_approved` ASC),
  INDEX `fid_area` (`fid_area` ASC),
  INDEX `fid_folder` (`fid_folder` ASC),
  INDEX `media_status` (`media_status` ASC),
  INDEX `media_type` (`media_type` ASC),
  INDEX `media_area` (`media_area` ASC),
  INDEX `media_timestamp` (`media_timestamp` ASC),
  INDEX `media_timestamp_desc` (`media_timestamp` DESC),
  INDEX `media_approved` (`media_approved` ASC),
  INDEX `media_classification` (`media_classification` ASC),
  FULLTEXT INDEX `media_tags` (`media_tags`),
  FULLTEXT INDEX `media_description` (`media_description`),
  INDEX `media_count_views` (`media_count_views` ASC),
  INDEX `media_count_views_desc` (`media_count_views` DESC),
  INDEX `media_count_downloads` (`media_count_downloads` ASC),
  INDEX `media_count_downloads_desc` (`media_count_downloads` DESC)
);
